project:
  type: website
  output-dir: docs
  render:
    - "**/*.qmd"

website:
  title: "Presentation template with Quarto and Revealjs"
  navbar:
    background: "#447099"
    left:
      - href: index.qmd
        text: Accueil
      - text: Cours
        menu: 
          - href: docs/cours/cm1.qmd
            text: "Cours n°1"
          - href: docs/cours/cm2.qmd
            text: "Cours n°2"
      - text: TP
        menu: 
          - href: docs/tp/tp1.md
            text: "TP n°1"
    right: 
      - href: "https://quarto.org/"
        text: "Quarto Docs"
      - icon: github
        href: https://github.com/ludo2ne/test-quarto

format:
  html:
    theme: 
      - solar
      - style.css
    toc: true



